author: 皮格·查尔斯
name: 皮格·查尔斯

title: 皮格·查尔斯
description: >- # this means to ignore newlines until "baseurl:"
  RADAR

email: hcheng1005@gmail.com


# social links
twitter_username: anxhe_
github_username:  anxhe
# rss: rss
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
#minima:
#  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# baseurl: http://127.0.0.1:4000
header_pages:
  - index.md
  - blog.md
  - doc.md

# Config section the home

# Build settings
markdown: kramdown

jekyll-theme-experiment:
  about:
    avatar : https://robohash.org/experiment-avatar.png?size=300x300

  portfolio:
    title: Portfolio
    projects:

      - name: 信号处理
        link: https://hcheng1005.github.io/signal_process.html
        github: https://www.baidu.com
        img_relative_url: /assets/example.png

      - name: 卡尔曼滤波
        link: https://hcheng1005.github.io/track.html
        github: https://hcheng1005.github.io/track.html
        img_relative_url: /assets/example.png
        
      - name: 关联算法
        link: https://hcheng1005.github.io/signal_process.html
        github: https://www.baidu.com
        img_relative_url: /assets/example.png

      - name: PHD
        github: https://www.baidu.com
        img_relative_url: /assets/example.png
        
        

  tools:
    title: Tools and Experience
    icons:
      - relative_url: /assets/icons/bitbucket/bitbucket-original.svg
      - relative_url: /assets/icons/heroku/heroku-original.svg
      - relative_url: /assets/icons/git/git-original.svg
      - relative_url: /assets/icons/express/express-original.svg
      - relative_url: /assets/icons/angularjs/angularjs-original.svg

exclude:
  - Gemfile
  - Gemfile.lock
  
plugins:
  - jekyll-pdf-embed
